### PR TITLE
Fixes issue #40 and #42

### LINKED ISSUE #40: Add expand/collapse option at TestClass level
The build logs for MATLAB tests execution would look cleaner if they would be together for each file/class, assuming TeamCity supports multi-level dropdowns with appropriate indentation. The title for test point dropdown can be updated accordingly.

### LINKED ISSUE #42: It would be nice if we had some sort of context before the first collapsable task name.
Refer to the screenshot below. At the moment, the first output that the user will see is the collapsable name of the task. This is great, but it might be even better if we gave some indication that it is a MBT task. Maybe something like "Task a" instead of just "a" or a header saying something like "Running build..." just to give people the context that the logs are showing an MBT build?

Image

### PR DESCRIPTION
**Pull request by tsharmaMW**
Resolves #40 , Resolves #42 

Here's a few snapshots:
image

Edit:
Reverted the prefix addition for the MBT task to maintain consistency across all plugins.
image

### CODE REVIEW

**Comment by sameagen-MW** [comment]
It seems like the naming pass decision for GHA was to just use the task name without context. To keep the plugins consistent, it's probably best to leave it as just the task name for now despite my preferences. I'll mesage you with the confluence link.

**Comment by tsharmaMW** [comment]
> It seems like the naming pass decision for GHA was to just use the task name without context. To keep the plugins consistent, it's probably best to leave it as just the task name for now despite my preferences. I'll mesage you with the confluence link.

Alright, it definitely makes sense to maintain consistency across all the plugins. I'll update the PR and also close issue #42.

File: matlab-plugin-agent/src/main/resources/+ciplugins/+teamcity/TestVisualizationPlugin.m [hunk 1]
```diff
@@ -4,6 +4,15 @@
 
     methods (Access=protected)
 
+        function runTestClass(plugin, pluginData)
+            disp("##teamcity[blockOpened name ='Running " + pluginData.Name + "']");
+
+            % Invoke the super class method
+            runTestClass@matlab.unittest.plugins.TestRunnerPlugin(plugin, pluginData);
+
+            disp("##teamcity[blockClosed name ='Running " + pluginData.Name + "']");
```
Comment (mw-kapilg) [inline matlab-plugin-agent/src/main/resources/+ciplugins/+teamcity/TestVisualizationPlugin.m:13]: Should the title of the group be just the name of the test file? else we'd start seeing "**Running TestFile**" statement twice in the logs (one because of the group title and another one from the Testing Framework).

Also it would be good to try running a non-class based tests (like script based tests) and see what happens in that case

Comment (tsharmaMW) [reply matlab-plugin-agent/src/main/resources/+ciplugins/+teamcity/TestVisualizationPlugin.m]: Revised the test group title and checked it with both script-based and function-based tests, and it seems to be working as expected. Attaching a snapshot for your reference-
image

**Review by mw-kapilg — APPROVED** [review]
LGTM! :shipit:

**Review by sameagen-MW — APPROVED** [review]
